# Projet 3

## Sommaire

[I. Préparation des données questions 1 à 14](#I.-Préparation-des-données-questions-1-à-14)

[1. Importation des bibliothèques](#1.-Importation-des-bibliothèques)

[2. Importation et réorganisation des données](#2.-Importation-et-réorganisation-des-données)

[a. Importation des données](#a.-Importation-des-données)

[b. Réorganisation des colonnes](#b.-Réorganisation-des-colonnes)

[ II. Questions 1 à 14](#II.-Questions-1-à-14)

[ Question 1](#Question-1)

[Question 2](#Question-2)

[Question 3](#Question-3)

[Question 4](#Question-4)

[Question 5](#Question-5)

[Question 6](#Question-6)

[Question 7](#Question-7)

[Question 8](#Question-8)

[Question 9](#Question-9)

[Question 10](#Question-10)

[Question 11](#Question-11)

[Question 12](#Question-12)

[Question 13](#Question-13)

[Question 14](#Question-14)

[III. Préparation des données questions 15 à 18](#III.-Préparation-des-données-questions-15-à-18)

[IV. Questions 15 à 18](#IV.-Questions-15-à-18)

[Question 15](#Question-15)

[Question 16](#Question-16)

[Question 17](#Question-17)

[Question 18](#Question-18)

[V. Exportation des données](#V.-Exportation-des-données)

## I. Préparation des données questions 1 à 14

### 1. Importation des bibliothèques

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### 2. Importation et réorganisation des données

#### a. Importation des tables

In [2]:
df_animal = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Animaux.csv')
df_vegetal = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Vegetaux.csv')
df_population = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Population.csv')
df_cereal = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Cereales.csv')
df_sous_alimentee = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Personnes_sous_alimentees.csv')

#### b. Réorganisation des colonnes

On commence par concaténer les tables "df_animal" et "df_vegetal"

Le fait d'ajouter une variable "origine" nous permettra de différencier les lignes de notre nouvelle table après concaténation, en fonction de leur table d'origine.

In [3]:
df_animal['origine'] = 'animal'
df_vegetal['origine'] = 'vegetal'

Il faut ensuite concaténer les tableaux, ceci équivaux à une union :

In [4]:
df_animal_vegetal = df_animal.append(df_vegetal)

Suppression des anciens talbeaux :

In [5]:
del df_animal, df_vegetal

Il faut désormais supprimer les colonnes inutiles de toutes nos tables:

In [6]:
df_animal_vegetal = df_animal_vegetal.drop(columns = ["Code Domaine","Domaine", "Code Élément","Code Année","Symbole", "Description du Symbole"],axis=1)

In [7]:
df_population.drop(columns = ["Code Domaine","Domaine","Code Élément","Code Année","Unité"],axis= 1,inplace = True)

In [8]:
df_cereal.drop(columns = ["Code Domaine","Domaine", "Code Élément","Code Année","Symbole", "Description du Symbole"], axis= 1, inplace = True)

In [9]:
df_sous_alimentee.drop(columns = ["Code Domaine","Domaine", "Unité", "Code Élément","Code année",],axis= 1,inplace = True)

On normalise le nom de leurs colonnes :

In [10]:
df_animal_vegetal.columns = ["code_pays", "pays", "element", "code_produit", "produit", "annee", "unite","valeur","origine"]

In [11]:
df_population.columns = ["code_pays", "pays", "element", "code_produit","produit", "annee", "population", "symbole", "description_symbole"]

In [12]:
df_cereal.columns = ["code_pays", "pays", "element", "code_produit", "produit", "annee", "unite","valeur",]

In [13]:
df_sous_alimentee.columns = ["code_pays", "pays", "element", "code_produit", "produit", "annee", "pop_sous_al", "symbole", "description_symbole"]

On muliplie par 1000 la colonne "Valeur" de la table population pour pouvoir l'appeler directement "population". On peut également faire disparaitre la colonne "Unité" qui n'a plus d'utilité. Tout ceci est fait en vu de la jointure nécessaire pour la question.

In [14]:
df_population.population = df_population.population * 1000

On change l'unité de la table `df_sous_alimentee`. Il faut dans un premier temps changer le type des valeurs qui est pour le  moment `object` en `float`, pour y parvenir nous retirons le caractère qui ne peut être converti :

In [15]:
df_sous_alimentee = df_sous_alimentee.loc[df_sous_alimentee.pop_sous_al.str.contains("<") == False]
df_sous_alimentee[['pop_sous_al']] = df_sous_alimentee[['pop_sous_al']].astype(float)
df_sous_alimentee[['pop_sous_al']] = df_sous_alimentee[['pop_sous_al']] * 1000000

Transformation des tables "df_animal_vegetal" et "cereales" en tableau croisé dynamique en veillant à convertir les nouvelles colonnes en kg :

In [16]:
df_animal_vegetal = df_animal_vegetal.pivot_table(
index=["code_pays","pays", "code_produit", "produit", "annee", "origine"],
    columns = ["element"], values=["valeur"], aggfunc=sum)

In [17]:
df_animal_vegetal.columns = ['alim_animaux_kg', 'autres_utilisations_kg', 'disponibilite_alimentaire_Kcal_personne_jour', 'disponibilite_alimentaire_kg_personne_an', 'disponibilite_de_matiere_grasse_en_quantite_g_personne_jour_', 'disponibilite_de_proteines_en_quantite_g_personne_jour', 'disponibilite_interieure_kg', 'exportations_quantite_kg', 'importations_quantite_kg', 'nourriture_kg', 'pertes_kg', 'production_kg', 'semences_kg', 'traitement_kg', 'variation_de_stock_kg']

In [18]:
df_animal_vegetal.alim_animaux_kg = df_animal_vegetal.alim_animaux_kg * 1000000
df_animal_vegetal.autres_utilisations_kg = df_animal_vegetal.autres_utilisations_kg * 1000000
df_animal_vegetal.disponibilite_interieure_kg = df_animal_vegetal.disponibilite_interieure_kg * 1000000
df_animal_vegetal.exportations_quantite_kg = df_animal_vegetal.exportations_quantite_kg * 1000000
df_animal_vegetal.importations_quantite_kg = df_animal_vegetal.importations_quantite_kg * 1000000
df_animal_vegetal.nourriture_kg = df_animal_vegetal.nourriture_kg * 1000000
df_animal_vegetal.pertes_kg = df_animal_vegetal.pertes_kg * 1000000
df_animal_vegetal.production_kg = df_animal_vegetal.production_kg * 1000000
df_animal_vegetal.semences_kg = df_animal_vegetal.semences_kg * 1000000
df_animal_vegetal.traitement_kg = df_animal_vegetal.traitement_kg * 1000000
df_animal_vegetal.variation_de_stock_kg = df_animal_vegetal.variation_de_stock_kg * 1000000

In [19]:
df_cereal = df_cereal.pivot_table(
index=["code_pays","pays", "code_produit", "produit", "annee",],
    columns = ["element"], values=["valeur"], aggfunc=sum)

In [20]:
df_cereal.columns = ['alim_animaux_kg', 'autres_utilisations_kg', 'disponibilite_alimentaire_Kcal_personne_jour', 'disponibilite_alimentaire_kg_personne_an',
                              'disponibilite_de_matiere_grasse_en_quantite_g_personne_jour_', 'disponibilite_de_proteines_en_quantite_g_personne_jour',
                             'disponibilite_interieure_kg', 'exportations_quantite_kg', 'importations_quantite_kg', 'nourriture_kg', 'pertes_kg', 'production_kg', 'semences_kg', 'traitement_kg', 'variation_de_stock_kg']

In [21]:
df_cereal.alim_animaux_kg = df_cereal.alim_animaux_kg * 1000000
df_cereal.autres_utilisations_kg = df_cereal.autres_utilisations_kg * 1000000
df_cereal.disponibilite_interieure_kg = df_cereal.disponibilite_interieure_kg * 1000000
df_cereal.exportations_quantite_kg = df_cereal.exportations_quantite_kg * 1000000
df_cereal.importations_quantite_kg = df_cereal.importations_quantite_kg * 1000000
df_cereal.nourriture_kg = df_cereal.nourriture_kg * 1000000
df_cereal.pertes_kg = df_cereal.pertes_kg * 1000000
df_cereal.production_kg = df_cereal.production_kg * 1000000
df_cereal.semences_kg = df_cereal.semences_kg * 1000000
df_cereal.traitement_kg = df_cereal.traitement_kg * 1000000
df_cereal.variation_de_stock_kg = df_cereal.variation_de_stock_kg * 1000000

Il est important de remettre les index à 0 pour qu'il remplisse encore leur fonction.

In [22]:
df_animal_vegetal = df_animal_vegetal.reset_index()

In [23]:
df_cereal = df_cereal.reset_index()

On défini une clé primaire parmi les clés candidates de nos tables, à l'aide d'une fonction. 
On retient comme clé candidate : ['pays', 'produit','unite']

In [24]:
def primary_key(dataframe,cle_candidate):
    if dataframe.dropna(subset=cle_candidate).drop_duplicates(subset=cle_candidate, keep=False).shape == dataframe.shape: 
        return print('This is a Primary key') 
    else: 
        return print('This might help you: https://en.wikipedia.org/wiki/Primary_key')

In [25]:
primary_key(df_animal_vegetal,['pays', 'produit'])

This is a Primary key

In [26]:
primary_key(df_population,['pays', 'produit'])

This is a Primary key

In [27]:
primary_key(df_cereal,["pays","produit"])

This is a Primary key

In [28]:
primary_key(df_sous_alimentee,['pays', 'produit'])

This is a Primary key

## II. Questions 1 à 14

### Question 1

En appliquant la fonction sum() à notre dataframe, on obtient la somme, pour chaque colonne, de toutes ses données.

In [29]:
df_population.sum()

code_pays                                                          22176
pays                   AfghanistanAfrique du SudAlbanieAlgérieAllemag...
element                Population totalePopulation totalePopulation t...
code_produit                                                      437675
produit                PopulationPopulationPopulationPopulationPopula...
annee                                                             352275
population                                                    8413993000
description_symbole    Donnée officielleDonnée officielleDonnée offic...
dtype: object

On constate que la somme de toutes les données de la colonne "valeur" donne un résultat de plus de 8,4 milliards d'habitants, alors que la Banque mondiale estime à environ 7,1 milliards le nombre d'habitants sur notre planète en 2013.

In [30]:
df_population.describe()

        code_pays  code_produit   annee    population
count  175.000000         175.0   175.0  1.750000e+02
mean   126.720000        2501.0  2013.0  4.807996e+07
std     75.168519           0.0     0.0  1.786327e+08
min      1.000000        2501.0  2013.0  5.400000e+04
25%     64.500000        2501.0  2013.0  2.543500e+06
50%    121.000000        2501.0  2013.0  9.413000e+06
75%    188.500000        2501.0  2013.0  2.888150e+07
max    351.000000        2501.0  2013.0  1.416667e+09

L'étude de la dispertion des données de notre dataframe ne nous permet pas d'identifier l'origne de l'anomalie constatée, en effet, les valeurs minimums et maximums présentées sont dans le bon ordre de grandeur.

In [31]:
df_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 9 columns):
code_pays              175 non-null int64
pays                   175 non-null object
element                175 non-null object
code_produit           175 non-null int64
produit                175 non-null object
annee                  175 non-null int64
population             175 non-null int64
symbole                1 non-null object
description_symbole    175 non-null object
dtypes: int64(4), object(5)
memory usage: 12.4+ KB

L'absence de valeur pour la colonne "Symbole" signifie qu'il s'agit d'une donnée officielle, comme l'indique les définitions du site FAOSTAT : http://www.fao.org/faostat/en/#definitions. Seule une ligne retranscrit des données issues d'une autre source, il s'agit d'un agrégat.

Nous nous interessons désormais aux lignes classées par ordre décroissant en fonction des données de la colonne "population".

In [32]:
df_population.sort_values(by = 'population', ascending = False).head()

,code_pays,pays,element,code_produit,produit,annee,population,symbole,description_symbole
174,351,Chine,Population totale,2501,Population,2013,1416667000,A,"Agrégat, peut inclure des données officielles,..."
35,41,"Chine, continentale",Population totale,2501,Population,2013,1385567000,NaN,Donnée officielle
73,100,Inde,Population totale,2501,Population,2013,1252140000,NaN,Donnée officielle
53,231,États-Unis d'Amérique,Population totale,2501,Population,2013,320051000,NaN,Donnée officielle
74,101,Indonésie,Population totale,2501,Population,2013,249866000,NaN,Donnée officielle

On constate que les deux premières lignes concernent la Chine, par ailleurs, l'une de ces deux lignes est celle dont les données sont issues d'un agrégat.

In [33]:
df_population[df_population['pays'].str.contains("Chine")]

,code_pays,pays,element,code_produit,produit,annee,population,symbole,description_symbole
33,96,Chine - RAS de Hong-Kong,Population totale,2501,Population,2013,7204000,NaN,Donnée officielle
34,128,Chine - RAS de Macao,Population totale,2501,Population,2013,566000,NaN,Donnée officielle
35,41,"Chine, continentale",Population totale,2501,Population,2013,1385567000,NaN,Donnée officielle
36,214,"Chine, Taiwan Province de",Population totale,2501,Population,2013,23330000,NaN,Donnée officielle
174,351,Chine,Population totale,2501,Population,2013,1416667000,A,"Agrégat, peut inclure des données officielles,..."

On constate que la population de la Chine est comptée deux fois.

In [34]:
df_population = df_population.drop(df_population[df_population.pays.isin(["Chine - RAS de Hong-Kong", "Chine - RAS de Macao","Chine, continentale","Chine, Taiwan Province de"])].index)

In [35]:
df_cereal = df_cereal.drop(df_cereal[df_cereal.pays.isin(["Chine - RAS de Hong-Kong", "Chine - RAS de Macao","Chine, continentale","Chine, Taiwan Province de"])].index)

In [36]:
df_animal_vegetal = df_animal_vegetal.drop(df_animal_vegetal[df_animal_vegetal.pays.isin(["Chine - RAS de Hong-Kong", "Chine - RAS de Macao","Chine, continentale","Chine, Taiwan Province de"])].index)

In [37]:
df_sous_alimentee = df_sous_alimentee.drop(df_sous_alimentee[df_sous_alimentee.pays.isin(["Chine - RAS de Hong-Kong", "Chine - RAS de Macao","Chine, continentale","Chine, Taiwan Province de"])].index)

In [38]:
population_mondiale = df_population.population.sum()
population_mondiale

6997326000

Le nouveau total est proche des estimations de la Banque mondiale. Considérant le fait que l'ONU en reconnais 197 au total, il est normal qu'il existe une marge d'erreur par rapport au chiffre comuniqué par la Banque mondiale.

### Question 2

In [39]:
df_cereal = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Cereales.csv')

On peut trouver la solution de notre équation à l'adresse suivante : http://www.fao.org/docrep/005/x9892f/x9892f03.htm
Ainsi on trouve : 

Disponibilité intérieure (Domestic supply)  = 

production_kg (production_kg) + Importations (Import Quantity) - Exportations (Export Quantity) + Variation de stock (Stock Variation) = 

semences_kg (Seed) + nourriture_kg (Food) + Aliments pour animaux (Feed) + traitement_kg (Processing) + Autres utilisations (Other uses) + pertes_kg (Waste) 

Cette équation montre l'approche par les emplois et l'approche par les ressources de la disponibilité intérieure.

On peut tester cette équation sur la production_kg de blé en France :

In [40]:
df_cereal.loc[(df_cereal['Pays'] == 'France' ) & (df_cereal['Produit'] == 'Blé')]

,Code Domaine,Domaine,Code Pays,Pays,Code Élément,Élément,Code Produit,Produit,Code Année,Année,Unité,Valeur,Symbole,Description du Symbole
5415,FBS,Bilans Alimentaires,68,France,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,38614.00,S,Données standardisées
5416,FBS,Bilans Alimentaires,68,France,5611,Importations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,2055.00,S,Données standardisées
5417,FBS,Bilans Alimentaires,68,France,5072,Variation de stock,2511,Blé,2013,2013,Milliers de tonnes,1131.00,S,Données standardisées
5418,FBS,Bilans Alimentaires,68,France,5911,Exportations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,21502.00,S,Données standardisées
5419,FBS,Bilans Alimentaires,68,France,5301,Disponibilité intérieure,2511,Blé,2013,2013,Milliers de tonnes,20298.00,S,Données standardisées
5420,FBS,Bilans Alimentaires,68,France,5521,Aliments pour animaux,2511,Blé,2013,2013,Milliers de tonnes,7822.00,S,Données standardisées
5421,FBS,Bilans Alimentaires,68,France,5527,Semences,2511,Blé,2013,2013,Milliers de tonnes,748.00,S,Données standardisées
5422,FBS,Bilans Alimentaires,68,France,5123,Pertes,2511,Blé,2013,2013,Milliers de tonnes,358.00,S,Données standardisées
5423,FBS,Bilans Alimentaires,68,France,5131,Traitement,2511,Blé,2013,2013,Milliers de tonnes,1575.00,S,Données standardisées
5424,FBS,Bilans Alimentaires,68,France,5154,Autres Utilisations,2511,Blé,2013,2013,Milliers de tonnes,2824.00,S,Données standardisées
5425,FBS,Bilans Alimentaires,68,France,5142,Nourriture,2511,Blé,2013,2013,Milliers de tonnes,6971.00,S,Données standardisées
5426,FBS,Bilans Alimentaires,68,France,645,Disponibilité alimentaire en quantité (kg/pers...,2511,Blé,2013,2013,kg,108.43,Fc,Donnée calculée
5427,FBS,Bilans Alimentaires,68,France,664,Disponibilité alimentaire (Kcal/personne/jour),2511,Blé,2013,2013,Kcal/personne/jour,811.00,Fc,Donnée calculée
5428,FBS,Bilans Alimentaires,68,France,674,Disponibilité de protéines en quantité (g/pers...,2511,Blé,2013,2013,g/personne/jour,25.99,Fc,Donnée calculée
5429,FBS,Bilans Alimentaires,68,France,684,Disponibilité de matière grasse en quantité (g...,2511,Blé,2013,2013,g/personne/jour,4.20,Fc,Donnée calculée

In [41]:
df_cereal.iloc[5419]['Valeur'] == df_cereal.iloc[5415]['Valeur'] + df_cereal.iloc[5416]['Valeur'] + df_cereal.iloc[5417]['Valeur'] - df_cereal.iloc[5418]['Valeur'] == df_cereal.iloc[5421]['Valeur'] + df_cereal.iloc[5425]['Valeur'] + df_cereal.iloc[5420]['Valeur'] + df_cereal.iloc[5423]['Valeur'] + df_cereal.iloc[5424]['Valeur'] + df_cereal.iloc[5422]['Valeur']

True

###  Question 3

Nous calculons pour chaque produit et chaque pays la disponiblité alimentaire en kcal et en kg de protéine.

In [42]:
df_disponibilite_al = df_animal_vegetal[['code_pays','pays', 'code_produit', 'produit', 'annee', 'origine',
       'alim_animaux_kg', 'autres_utilisations_kg',
       'disponibilite_alimentaire_Kcal_personne_jour',
       'disponibilite_alimentaire_kg_personne_an',
       'disponibilite_de_matiere_grasse_en_quantite_g_personne_jour_',
       'disponibilite_de_proteines_en_quantite_g_personne_jour',
       'disponibilite_interieure_kg', 'exportations_quantite_kg',
       'importations_quantite_kg', 'nourriture_kg', 'pertes_kg', 'production_kg',
       'semences_kg', 'traitement_kg', 'variation_de_stock_kg']]

Nous créons une nouvelle table en faisant un jointure interne avec la table "df_population", ainsi nous pouvons ajouter pour chaque pays sa population.

Le paramètre `indicator=True` va nous permettre d'ajouter une colonne qui indique si la jointure a fonctionnée sur toutes les lignes de deux tables. En effet, une colonne `_merge` est ajoutée et et elle indique si il existe une équivalence entre les deux tables pour une ligne donnée.

In [43]:
df_disponibilite_al = df_disponibilite_al.merge(df_population[["pays", "population"]], how='outer', on=['pays'], indicator=True)
df_disponibilite_al = df_disponibilite_al.reset_index()

In [44]:
# On vérifie si il n'y a pas de ligne exclusive au tableau droit.
df_disponibilite_al.loc[df_disponibilite_al['_merge'] == 'right_only' ]

Empty DataFrame
Columns: [index, code_pays, pays, code_produit, produit, annee, origine, alim_animaux_kg, autres_utilisations_kg, disponibilite_alimentaire_Kcal_personne_jour, disponibilite_alimentaire_kg_personne_an, disponibilite_de_matiere_grasse_en_quantite_g_personne_jour_, disponibilite_de_proteines_en_quantite_g_personne_jour, disponibilite_interieure_kg, exportations_quantite_kg, importations_quantite_kg, nourriture_kg, pertes_kg, production_kg, semences_kg, traitement_kg, variation_de_stock_kg, population, _merge]
Index: []

[0 rows x 24 columns]

In [45]:
# On vérifie si il n'y a pas de ligne exclusive au tableau gauche.
df_disponibilite_al.loc[df_disponibilite_al['_merge'] == 'left_only' ]

Empty DataFrame
Columns: [index, code_pays, pays, code_produit, produit, annee, origine, alim_animaux_kg, autres_utilisations_kg, disponibilite_alimentaire_Kcal_personne_jour, disponibilite_alimentaire_kg_personne_an, disponibilite_de_matiere_grasse_en_quantite_g_personne_jour_, disponibilite_de_proteines_en_quantite_g_personne_jour, disponibilite_interieure_kg, exportations_quantite_kg, importations_quantite_kg, nourriture_kg, pertes_kg, production_kg, semences_kg, traitement_kg, variation_de_stock_kg, population, _merge]
Index: []

[0 rows x 24 columns]

Toutes les lignes sont jointes.

Nous créons désormais les nouvelles colonnes, il faut au préalable changer l'unité de la colonne `disponibilite_alimentaire_kg_personne_an` en la multipliant par la population pour avoir un résultat représentatif des pays  en entier.

In [46]:
# Nous renommerons par la suite la colonne pour qu'elle corresponde à ce changement d'unité.
df_disponibilite_al.disponibilite_alimentaire_kg_personne_an = (df_disponibilite_al.disponibilite_alimentaire_kg_personne_an) * (df_disponibilite_al.population)

In [47]:
df_disponibilite_al['disponibilite_alimentaire_kcal_pays_an'] = (df_disponibilite_al.disponibilite_alimentaire_Kcal_personne_jour) * (df_disponibilite_al.population) * 365
df_disponibilite_al['disponibilite_proteine_quantite_kg_pays_an'] = ((df_disponibilite_al.disponibilite_de_proteines_en_quantite_g_personne_jour)/1000) * (df_disponibilite_al.population)*365

In [48]:
df_disponibilite_al.drop(columns = ["index", "disponibilite_alimentaire_Kcal_personne_jour", "disponibilite_de_proteines_en_quantite_g_personne_jour", "_merge"], axis= 1, inplace = True)

In [49]:
df_disponibilite_al.head()

,code_pays,pays,code_produit,produit,annee,origine,alim_animaux_kg,autres_utilisations_kg,disponibilite_alimentaire_kg_personne_an,disponibilite_de_matiere_grasse_en_quantite_g_personne_jour_,...,importations_quantite_kg,nourriture_kg,pertes_kg,production_kg,semences_kg,traitement_kg,variation_de_stock_kg,population,disponibilite_alimentaire_kcal_pays_an,disponibilite_proteine_quantite_kg_pays_an
0,1,Arménie,2511,Blé,2013,vegetal,93000000.0,0.0,388796200.0,3.60,...,361000000.0,389000000.0,32000000.0,312000000.0,30000000.0,10000000.0,-118000000.0,2977000,1.112684e+12,33163184.60
1,1,Arménie,2513,Orge,2013,vegetal,137000000.0,26000000.0,0.0,0.00,...,9000000.0,0.0,15000000.0,189000000.0,14000000.0,7000000.0,0.0,2977000,0.000000e+00,0.00
2,1,Arménie,2514,Maïs,2013,vegetal,96000000.0,NaN,89310.0,NaN,...,82000000.0,0.0,7000000.0,21000000.0,0.0,NaN,NaN,2977000,0.000000e+00,10866.05
3,1,Arménie,2515,Seigle,2013,vegetal,1000000.0,NaN,357240.0,0.00,...,0.0,0.0,0.0,1000000.0,0.0,NaN,0.0,2977000,1.086605e+09,21732.10
4,1,Arménie,2516,Avoine,2013,vegetal,4000000.0,NaN,1101490.0,0.03,...,1000000.0,1000000.0,0.0,5000000.0,0.0,NaN,NaN,2977000,2.173210e+09,97794.45

In [50]:
df_disponibilite_al.columns = ["code_pays", "pays", "code_produit", "produit", 'annee', 'origine', 'alim_animaux_kg',
       'autres_utilisations_kg',
       'disponibilite_alimentaire_kg_pays_an',
       'disponibilite_de_matiere_grasse_en_quantite_g_personne_jour_',
       'disponibilite_interieure_kg', 'exportations_quantite_kg',
       'importations_quantite_kg', 'nourriture_kg', 'pertes_kg', 'production_kg',
       'semences_kg', 'traitement_kg', 'variation_de_stock_kg', 'population',
       'disponibilite_alimentaire_kcal_pays_an',
       'disponibilite_proteine_quantite_kg_pays_an']

###  Question 4

Nous supprimons toutes les valeurs nulles de la colonne `df_disponibilite_al.disponibilite_alimentaire_kg_pays_an` pour éviter les valeurs infinies :

In [51]:
df_disponibilite_al = df_disponibilite_al.loc[( df_disponibilite_al.disponibilite_alimentaire_kg_pays_an > 0)] 
df_disponibilite_al = df_disponibilite_al.reset_index(drop=True)

Nous créons les colonnes "ratio_energie_poids" et "pourcentage_proteine_poids":

In [52]:
 df_disponibilite_al['ratio_energie_poids'] = (df_disponibilite_al.disponibilite_alimentaire_kcal_pays_an) / (df_disponibilite_al.disponibilite_alimentaire_kg_pays_an)

In [53]:
 df_disponibilite_al['pourcentage_proteine_poids'] = ((df_disponibilite_al.disponibilite_proteine_quantite_kg_pays_an) / (df_disponibilite_al.disponibilite_alimentaire_kg_pays_an)) * 100

Pour vérifier la cohérence des valeurs trouvées on compare la valeur moyenne du ratio kcal/kg pour les oeufs de notre table avec des données extérieures à notre table :

In [54]:
df_disponibilite_al.ratio_energie_poids[df_disponibilite_al.produit == 'Oeufs'].mean()

1363.8628304280364

On vérifie le ratio en le comparant avec celui calculable via une autre source : https://fr.wikipedia.org/wiki/%C5%92uf_(aliment)

Valeur calorique des oeufs 147 kcal pour 100 g. On peut calculer ce ratio en convertissant les grammes en kilogrammes.

In [55]:
147/0.1

1470.0

L'ordre de grandeur est respecté, les données semblent cohérentes.

Nous vérifions de la même manière que la pourcentage de protéines dans l'avoine est conforme à nos attentes.

In [56]:
df_disponibilite_al.pourcentage_proteine_poids[df_disponibilite_al.produit == 'Avoine'].mean()

7.937557143325648

L'ordre de grandeur respecte celui de la source suivante : https://fr.wikipedia.org/wiki/Avoine_cultiv%C3%A9e.
En effet le résultat doit être proche des 10%.

### Question 5

Nous créons une nouvelle table "df_top20" pour afficher les 20 aliments les plus caloriques et les 20 ayant le plus haut taux de protéines, à partir de la table "df_disponibilite_al". Nous commençons par supprimer les colonnes inutiles pour cette démonstration :

In [57]:
df_top20 = df_disponibilite_al[['pays', 'produit', 'origine', 'ratio_energie_poids','pourcentage_proteine_poids']]

Nous retirons toutes les valeurs `NaN` :

In [58]:
df_top20 = df_top20.dropna()

Nous retirons les valeurs nulles :

In [59]:
df_top20 = df_top20.loc[(df_top20.ratio_energie_poids > 0)] 
df_top20 = df_top20.loc[((df_top20.pourcentage_proteine_poids
 > 0))]

Nous regroupons les lignes par produit et calculons la moyenne du ratio étudié :

In [60]:
df_top20 = df_top20.groupby('produit').mean()

Nous trouvons finalement les 20 produits les plus caloriques, les 5 premiers étant l'huile de foie de poisson, l'huile de sésame, l'huile de son de riz, l'huile d'olive et l'huile de germe de maïs.

In [61]:
df_top20.columns = ['ratio_energie_poids_moyen','pourcentage_proteine_poids_moyen']

In [62]:
df_top20.sort_values(by = 'ratio_energie_poids_moyen', ascending = False).head(20)

,ratio_energie_poids_moyen,pourcentage_proteine_poids_moyen
produit,,
Huile d'Arachide,9125.000000,1.013889
Huile de Germe de Maïs,8859.395213,0.763171
Huil Plantes Oleif Autr,8858.323861,1.071149
Huile de Tournesol,8814.348634,0.284051
Huile de Palme,8655.326472,0.499203
Huile de Soja,8640.103986,0.322562
Huile de Colza&Moutarde,8568.326652,0.394392
Huile Graines de Coton,8540.077671,0.561238
Huile de Coco,8332.185788,0.736426
Huile de Palmistes,8312.197365,0.644910
Huile de Son de Riz,8264.150943,0.688679
Graisses Animales Crue,7569.692864,1.598319
"Beurre, Ghee",7282.544898,0.919332
Sésame,6142.036023,18.031160
Arachides Decortiquees,5705.037380,25.028144
Feve de Cacao,4838.330007,7.649702
"Plantes Oleiferes, Autre",4836.718946,18.183118
Graines Colza/Moutarde,4380.000000,36.500000
Aliments pour enfants,3826.241780,15.331439
Girofles,3721.654647,5.854582

Parmis les 20 aliments les plus caloriques nous pouvont citer l'huile d'arachide, l'huile de germe de maïs, l'huile de tournesol, l'huile de palme et l'huile de soja.

In [63]:
df_top20.sort_values(by = 'pourcentage_proteine_poids_moyen', ascending = False).head(20)

,ratio_energie_poids_moyen,pourcentage_proteine_poids_moyen
produit,,
Graines Colza/Moutarde,4380.000000,36.500000
Soja,3224.862660,31.753451
Arachides Decortiquees,5705.037380,25.028144
Pois,3526.471760,22.297166
Légumineuses Autres,3481.584429,22.149204
Haricots,3428.739834,21.855126
"Plantes Oleiferes, Autre",4836.718946,18.183118
Sésame,6142.036023,18.031160
Abats Comestible,1133.032816,17.616939
"Viande, Autre",1373.350862,17.525760
Aliments pour enfants,3826.241780,15.331439
Viande de Bovins,1695.163326,14.456889
Cephalopodes,910.596193,14.405657
Viande d'Ovins/Caprins,2036.012852,13.861137
Viande de Volailles,1299.475855,12.623639
Piments,3486.362326,12.356682
Poissons Pelagiques,974.091972,12.323581
Graines de tournesol,3407.463766,11.605517
"Poissons Marins, Autres",790.280395,11.444467
"Épices, Autres",3589.309645,10.878666

Nous pouvons citer comme faisant partis des 5 aliments ayant la plus grande concentration en protéine le soja , l'arachides decortiquées, les pois, les haricots, le sésame.

Voir : https://fr.wikipedia.org/wiki/Score_chimique_corrig%C3%A9_de_la_digestibilit%C3%A9

### Question 6

Nous commençons par intégrer à notre table `df_disponibilite_al` les ratios et pourcentages moyens calculés pour la question précédente, via une jointure :

In [64]:
df_disponibilite_al = df_disponibilite_al.merge(df_top20[['ratio_energie_poids_moyen','pourcentage_proteine_poids_moyen']], how='outer', on=['produit'], indicator=True)

In [65]:
df_disponibilite_al.loc[df_disponibilite_al['_merge'] == 'right_only' ]

Empty DataFrame
Columns: [code_pays, pays, code_produit, produit, annee, origine, alim_animaux_kg, autres_utilisations_kg, disponibilite_alimentaire_kg_pays_an, disponibilite_de_matiere_grasse_en_quantite_g_personne_jour_, disponibilite_interieure_kg, exportations_quantite_kg, importations_quantite_kg, nourriture_kg, pertes_kg, production_kg, semences_kg, traitement_kg, variation_de_stock_kg, population, disponibilite_alimentaire_kcal_pays_an, disponibilite_proteine_quantite_kg_pays_an, ratio_energie_poids, pourcentage_proteine_poids, ratio_energie_poids_moyen, pourcentage_proteine_poids_moyen, _merge]
Index: []

[0 rows x 27 columns]

In [66]:
df_disponibilite_al[['pays','produit','disponibilite_alimentaire_kg_pays_an', 'disponibilite_alimentaire_kcal_pays_an', 'disponibilite_proteine_quantite_kg_pays_an', 'ratio_energie_poids_moyen', 'pourcentage_proteine_poids_moyen']] .loc[df_disponibilite_al['_merge'] == 'left_only']

,pays,produit,disponibilite_alimentaire_kg_pays_an,disponibilite_alimentaire_kcal_pays_an,disponibilite_proteine_quantite_kg_pays_an,ratio_energie_poids_moyen,pourcentage_proteine_poids_moyen
852,Arménie,Sucre Eq Brut,9.833031e+07,3.281547e+11,NaN,NaN,NaN
853,Afghanistan,Sucre Eq Brut,2.551092e+08,9.367243e+11,NaN,NaN,NaN
854,Albanie,Sucre Eq Brut,5.552750e+07,2.003591e+11,NaN,NaN,NaN
855,Algérie,Sucre Eq Brut,1.089198e+09,3.692217e+12,NaN,NaN,NaN
856,Angola,Sucre Eq Brut,3.265891e+08,1.073707e+12,NaN,NaN,NaN
857,Antigua-et-Barbuda,Sucre Eq Brut,2.503800e+06,9.132300e+09,NaN,NaN,NaN
858,Argentine,Sucre Eq Brut,1.717522e+09,6.096499e+12,NaN,NaN,NaN
859,Australie,Sucre Eq Brut,8.510858e+08,3.143952e+12,NaN,NaN,NaN
860,Autriche,Sucre Eq Brut,3.358923e+08,1.206163e+12,NaN,NaN,NaN
861,Bahamas,Sucre Eq Brut,1.115166e+07,4.196952e+10,NaN,NaN,NaN
862,Barbade,Sucre Eq Brut,1.588020e+07,5.596545e+10,NaN,NaN,NaN
863,Bangladesh,Sucre Eq Brut,8.534428e+08,3.029330e+12,NaN,NaN,NaN
864,Bermudes,Sucre Eq Brut,1.492400e+06,5.575375e+09,NaN,NaN,NaN
865,Bolivie (État plurinational de),Sucre Eq Brut,2.838486e+08,1.028258e+12,NaN,NaN,NaN
866,Botswana,Sucre Eq Brut,5.109088e+07,1.822033e+11,NaN,NaN,NaN
867,Brésil,Sucre Eq Brut,7.936339e+09,2.822900e+13,NaN,NaN,NaN
868,Belize,Sucre Eq Brut,1.365848e+07,4.907790e+10,NaN,NaN,NaN
869,Îles Salomon,Sucre Eq Brut,2.272050e+06,8.395365e+09,NaN,NaN,NaN
870,Brunéi Darussalam,Sucre Eq Brut,1.205094e+07,4.409273e+10,NaN,NaN,NaN
871,Bulgarie,Sucre Eq Brut,1.902538e+08,6.749171e+11,NaN,NaN,NaN
872,Myanmar,Sucre Eq Brut,3.089022e+07,1.166372e+11,NaN,NaN,NaN
873,Cameroun,Sucre Eq Brut,2.129708e+08,7.472893e+11,NaN,NaN,NaN
874,Canada,Sucre Eq Brut,1.136027e+09,4.276196e+12,NaN,NaN,NaN
875,Cabo Verde,Sucre Eq Brut,8.937090e+06,3.260216e+10,NaN,NaN,NaN
876,République centrafricaine,Sucre Eq Brut,2.155672e+07,7.750264e+10,NaN,NaN,NaN
877,Sri Lanka,Sucre Eq Brut,5.603308e+08,2.065396e+12,NaN,NaN,NaN
878,Tchad,Sucre Eq Brut,1.335082e+08,4.774748e+11,NaN,NaN,NaN
879,Chili,Sucre Eq Brut,7.893760e+08,2.791184e+12,NaN,NaN,NaN
880,Colombie,Sucre Eq Brut,1.602808e+09,5.696804e+12,NaN,NaN,NaN
881,Congo,Sucre Eq Brut,7.717280e+07,2.759984e+11,NaN,NaN,NaN
...,...,...,...,...,...,...,...
10028,Tunisie,Huile de Sésame,2.199400e+05,4.013905e+09,NaN,NaN,NaN
10029,Turquie,Huile de Sésame,3.147186e+07,2.735054e+11,NaN,NaN,NaN
10030,Émirats arabes unis,Huile de Sésame,4.673000e+05,3.411290e+09,NaN,NaN,NaN
10031,Ouganda,Huile de Sésame,2.555372e+07,2.194614e+11,NaN,NaN,NaN
10032,Royaume-Uni,Huile de Sésame,2.535360e+06,2.313516e+10,NaN,NaN,NaN
10033,Burkina Faso,Huile de Sésame,1.693500e+05,0.000000e+00,NaN,NaN,NaN
10034,Venezuela (République bolivarienne du),Huile de Sésame,6.081000e+05,0.000000e+00,NaN,NaN,NaN
10035,Viet Nam,Huile de Sésame,3.667200e+06,3.346320e+10,NaN,NaN,NaN
10036,Yémen,Huile de Sésame,8.786520e+06,8.017700e+10,NaN,NaN,NaN
10037,Soudan,Huile de Sésame,3.037120e+07,2.632803e+11,NaN,NaN,NaN
10038,Chine,Huile de Sésame,2.266667e+08,2.068334e+12,NaN,NaN,NaN
11674,Australie,Huiles de Foie de Poisso,2.334300e+05,0.000000e+00,0.0,NaN,NaN
11675,Estonie,Huiles de Foie de Poisso,1.287000e+04,0.000000e+00,0.0,NaN,NaN
11676,France,Huiles de Foie de Poisso,6.429100e+05,0.000000e+00,0.0,NaN,NaN
11677,Islande,Huiles de Foie de Poisso,1.683000e+05,1.565850e+09,0.0,NaN,NaN
11678,Irlande,Huiles de Foie de Poisso,4.627000e+04,0.000000e+00,0.0,NaN,NaN
11679,Italie,Huiles de Foie de Poisso,6.099000e+05,0.000000e+00,0.0,NaN,NaN
11680,Malaisie,Huiles de Foie de Poisso,2.080190e+06,2.169341e+10,0.0,NaN,NaN
11681,Maroc,Huiles de Foie de Poisso,3.300800e+05,0.000000e+00,0.0,NaN,NaN
11682,Pologne,Huiles de Foie de Poisso,3.821700e+05,0.000000e+00,0.0,NaN,NaN
11683,Portugal,Huiles de Foie de Poisso,2.121600e+05,3.871920e+09,0.0,NaN,NaN
11684,Trinité-et-Tobago,Huiles de Foie de Poisso,1.341000e+04,0.000000e+00,0.0,NaN,NaN
11685,Uruguay,Huiles de Foie de Poisso,3.407000e+04,0.000000e+00,0.0,NaN,NaN
11686,Belgique,Huiles de Foie de Poisso,7.883840e+06,7.295328e+10,0.0,NaN,NaN
11773,Congo,Palmistes,4.448000e+06,2.435280e+10,0.0,NaN,NaN
11774,Danemark,Huiles de Poissons,2.045316e+07,1.845842e+11,0.0,NaN,NaN
11775,France,Huiles de Poissons,1.607275e+07,1.407973e+11,0.0,NaN,NaN
11776,Japon,Huiles de Poissons,3.178600e+07,2.784454e+11,0.0,NaN,NaN
11777,Portugal,Huiles de Poissons,4.243200e+05,3.871920e+09,0.0,NaN,NaN
11778,Slovénie,Huiles de Poissons,2.072000e+04,0.000000e+00,0.0,NaN,NaN

In [67]:
df_disponibilite_al = df_disponibilite_al.loc[df_disponibilite_al['_merge'] != 'left_only']
df_disponibilite_al = df_disponibilite_al.reset_index(drop=True)

In [68]:
df_disponibilite_al.drop(columns = ['ratio_energie_poids','pourcentage_proteine_poids','_merge'], axis=1, inplace=True)

Pour quelques produits, nous n'avons pas de ratio kcal/kg moyen ou de pourcentage de protéine moyen, nous faisons donc une restriction en retirant ces lignes.

Nous calculons désormais la disponibilité intérieur en kcal du monde :

In [69]:
df_disponibilite_al['dispo_inter_kcal'] = df_disponibilite_al.disponibilite_interieure_kg * df_disponibilite_al.ratio_energie_poids_moyen

In [70]:
df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['dispo_inter_kcal']].sum()

dispo_inter_kcal    1.206465e+16
dtype: float64

### Question 7

Source : http://www.fao.org/docrep/003/aa040e/AA040E06.htm

En comparant plusieurs sources trouvées sur internet et en comparant les besoins des différentes catégories d'individus, nous estimerons que le besoin journalier en kcal pour une personne est de 2030 kcal/jour. En partant de ce postulat, nous calculons le besoin annuel nous calculons un besoin théorique en kcal par année et par personne.

In [71]:
besoin_kcal_personne_annuel =  2030 * 365

Nous calculons la disponibilité intérieure mondiale pour les produits végétaux :

In [72]:
df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['dispo_inter_kcal']].sum()

dispo_inter_kcal    1.206465e+16
dtype: float64

Nous calculons ensuite la population pouvant être statisfaite par la disponibilité intérieure en kcal :

In [73]:
df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['dispo_inter_kcal']].sum() / besoin_kcal_personne_annuel

dispo_inter_kcal    1.628268e+10
dtype: float64

Nous finissions par calculer cette satisfaction en pourcentage de la population mondiale :

In [74]:
(((df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['dispo_inter_kcal']].sum()) / besoin_kcal_personne_annuel) / population_mondiale) *100

dispo_inter_kcal    232.698635
dtype: float64

Nous effectuons les mêmes calculs avec la satisfaction des besoins en protéines. La FAO recommande 0,0008 kg de protéine par kg de poids corporel. Nous prendrons comme réfèrence une personne de 70 kg.

In [75]:
besoin_proteine_personne_annuel = 0.0008 * 70 * 365

In [76]:
df_disponibilite_al['dispo_inter_proteine'] = df_disponibilite_al.disponibilite_interieure_kg * df_disponibilite_al.pourcentage_proteine_poids_moyen / 100

In [77]:
df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['dispo_inter_proteine']].sum()

dispo_inter_proteine    3.167134e+11
dtype: float64

In [78]:
df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['dispo_inter_proteine']].sum() / besoin_proteine_personne_annuel

dispo_inter_proteine    1.549478e+10
dtype: float64

In [79]:
(((df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['dispo_inter_proteine']].sum()) / besoin_proteine_personne_annuel) / population_mondiale) * 100

dispo_inter_proteine    221.438649
dtype: float64

### Question 8

Nous cherchons à calculer le nombre total de personnes pouvant être satisfaites par les produits d'origine végétale déstinés à l'alimentation des humains, aux animaux et ceux gachés en val. Nous commençons par étudier la satisfactions de ces besoins d'un point de vu calorique :

In [80]:
df_disponibilite_al['humains_animaux_pertes_kcal'] = (df_disponibilite_al.disponibilite_alimentaire_kg_pays_an + df_disponibilite_al.alim_animaux_kg + df_disponibilite_al.pertes_kg) *  df_disponibilite_al.ratio_energie_poids_moyen

In [81]:
df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['humains_animaux_pertes_kcal']].sum() / besoin_kcal_personne_annuel

humains_animaux_pertes_kcal    8.411233e+09
dtype: float64

Nombre de personne pouvant être satisfaites d'un point de vu calorique, en pourcentage de la population mondiale :

In [82]:
((df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['humains_animaux_pertes_kcal']].sum() / besoin_kcal_personne_annuel) / population_mondiale) *100

humains_animaux_pertes_kcal    120.206394
dtype: float64

Nous abordons cette même question du point de vue de l'apport en protéine :

In [83]:
df_disponibilite_al['humains_animaux_pertes_proteine'] = (df_disponibilite_al.disponibilite_alimentaire_kg_pays_an + df_disponibilite_al.alim_animaux_kg + df_disponibilite_al.pertes_kg) * df_disponibilite_al.pourcentage_proteine_poids_moyen / 100

Nombre total de personnes pouvant être satisfaites d'un point de vu protéinique :

In [84]:
df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['humains_animaux_pertes_proteine']].sum() / besoin_proteine_personne_annuel

humains_animaux_pertes_proteine    7.958054e+09
dtype: float64

Nombre de personnes pouvant être satisfaites d'un point de vu protéinique, en pourcentage de la population :

In [85]:
((df_disponibilite_al.loc[(df_disponibilite_al.origine == 'vegetal'), ['humains_animaux_pertes_proteine']].sum() / besoin_proteine_personne_annuel) / population_mondiale) *100

humains_animaux_pertes_proteine    113.729933
dtype: float64

###  Question 9

Nous cherchons à déterminer le nombre de personnes pouvant être satisfaites par la disponibilité alimentaire végétale d'un point de vue des calories d'une part et de celui des protéines d'autre part. 

Nous commençons par calculer la disponibilité alimentaire mondiale d'un poit de vu calorique et protéinique via deux nouvelles colonnes :

In [86]:
df_disponibilite_al['dispo_alim_kcal_mondiale_annuelle'] = df_disponibilite_al['disponibilite_alimentaire_kg_pays_an'] * df_disponibilite_al['ratio_energie_poids_moyen']
df_disponibilite_al['dispo_alim_proteine_mondiale_annuelle'] = df_disponibilite_al['disponibilite_alimentaire_kg_pays_an'] * df_disponibilite_al['pourcentage_proteine_poids_moyen'] / 100

Résultat total pour les calories :

In [87]:
df_disponibilite_al['dispo_alim_kcal_mondiale_annuelle'].loc[df_disponibilite_al.origine == 'vegetal'].sum() / besoin_kcal_personne_annuel

7417066348.285207

Résultat pour les calories en pourcentage de la population mondiale :

In [88]:
((df_disponibilite_al['dispo_alim_kcal_mondiale_annuelle'].loc[df_disponibilite_al.origine == 'vegetal'].sum() / besoin_kcal_personne_annuel) / population_mondiale) * 100

105.99858214816926

Résultat total pour les protéines :

Résultat pour les protéines en pourcentage de la population mondiale :

In [89]:
df_disponibilite_al['dispo_alim_proteine_mondiale_annuelle'].loc[df_disponibilite_al.origine == 'vegetal'].sum() / besoin_proteine_personne_annuel

6035864469.552949

In [90]:
((df_disponibilite_al['dispo_alim_proteine_mondiale_annuelle'].loc[df_disponibilite_al.origine == 'vegetal'].sum() / besoin_proteine_personne_annuel)/ population_mondiale) * 100

86.25958644134843

### Question 10

Nous calculons, approximativement, le pourcentage de la popluation mondiale, souffrant de malnutrition :

In [91]:
100 * df_sous_alimentee['pop_sous_al'].sum() / population_mondiale

10.572610165654709

### Question 11

Nous créons une nouvelle colonne de type booléen, qui va nous permettre d'identifier les produits qui sont des céréales :

In [92]:
df_disponibilite_al['is_cereal'] = df_disponibilite_al['produit'].isin(df_cereal['Produit'])

In [93]:
df_disponibilite_al[["code_produit", "produit"]].loc[df_disponibilite_al.is_cereal == True].drop_duplicates()

       code_produit           produit
0              2511               Blé
171            2514              Maïs
334            2515            Seigle
408            2516            Avoine
537            2520  Céréales, Autres
8700           2805  Riz (Eq Blanchi)
9042           2513              Orge
9160           2517            Millet
10439          2518            Sorgho

Proportion, en pourcentage, des céréales destinés à l'alimentation des animaux :

In [94]:
disponibilité_al_cereal_kg_monde_an = df_disponibilite_al['disponibilite_alimentaire_kg_pays_an'].loc[df_disponibilite_al.is_cereal == True].sum()

In [95]:
disponibilité_al_animaux_cereal_kg_monde_an = df_disponibilite_al['alim_animaux_kg'].loc[df_disponibilite_al.is_cereal == True].sum()

In [96]:
100 * disponibilité_al_animaux_cereal_kg_monde_an / (disponibilité_al_animaux_cereal_kg_monde_an + disponibilité_al_cereal_kg_monde_an)

44.912342315735046

### Question 12

Nous cherchons les pays présent dans `df_disponibilite_al` et `df_sous_alimentee` en vayant bien à éliminer les valeurs `Nan` :

In [97]:
df_sous_alimentee = df_sous_alimentee.dropna()

In [98]:
df_disponibilite_al = df_disponibilite_al.merge(df_sous_alimentee[['pop_sous_al','pays']], how='outer', on=['pays'], indicator=True)
df_disponibilite_al = df_disponibilite_al.reset_index(drop=True)

In [99]:
df_disponibilite_al.loc[df_disponibilite_al['_merge'] == 'left_only']

,code_pays,pays,code_produit,produit,annee,origine,alim_animaux_kg,autres_utilisations_kg,disponibilite_alimentaire_kg_pays_an,disponibilite_de_matiere_grasse_en_quantite_g_personne_jour_,...,pourcentage_proteine_poids_moyen,dispo_inter_kcal,dispo_inter_proteine,humains_animaux_pertes_kcal,humains_animaux_pertes_proteine,dispo_alim_kcal_mondiale_annuelle,dispo_alim_proteine_mondiale_annuelle,is_cereal,pop_sous_al,_merge
290,8,Antigua-et-Barbuda,2511,Blé,2013,vegetal,NaN,1000000.0,5585400.0,4.84,...,8.199951,1.994892e+10,5.739966e+05,NaN,NaN,1.591752e+10,4.580001e+05,True,NaN,left_only
291,8,Antigua-et-Barbuda,2514,Maïs,2013,vegetal,0.0,NaN,219600.0,0.24,...,7.215960,0.000000e+00,0.000000e+00,6.632362e+08,1.584625e+04,6.632362e+08,1.584625e+04,True,NaN,left_only
292,8,Antigua-et-Barbuda,2515,Seigle,2013,vegetal,NaN,NaN,900.0,NaN,...,7.247613,0.000000e+00,0.000000e+00,NaN,NaN,2.470915e+06,6.522852e+01,True,NaN,left_only
293,8,Antigua-et-Barbuda,2516,Avoine,2013,vegetal,0.0,NaN,240300.0,0.24,...,8.629383,0.000000e+00,0.000000e+00,NaN,NaN,5.401464e+08,2.073641e+04,True,NaN,left_only
294,8,Antigua-et-Barbuda,2520,"Céréales, Autres",2013,vegetal,NaN,NaN,90900.0,0.03,...,7.677597,0.000000e+00,0.000000e+00,NaN,NaN,2.643904e+08,6.978936e+03,True,NaN,left_only
295,8,Antigua-et-Barbuda,2531,Pommes de Terre,2013,vegetal,0.0,1000000.0,1406700.0,0.03,...,1.475149,1.343298e+09,2.950299e+04,9.448085e+08,2.075092e+04,9.448085e+08,2.075092e+04,False,NaN,left_only
296,8,Antigua-et-Barbuda,2543,Edulcorants Autres,2013,vegetal,NaN,1000000.0,419400.0,NaN,...,0.171446,2.841382e+09,1.714463e+03,NaN,NaN,1.191676e+09,7.190457e+02,False,NaN,left_only
297,8,Antigua-et-Barbuda,2551,Noix,2013,vegetal,NaN,0.0,62100.0,0.43,...,6.929250,0.000000e+00,0.000000e+00,NaN,NaN,1.638297e+08,4.303064e+03,False,NaN,left_only
298,8,Antigua-et-Barbuda,2556,Arachides Decortiquees,2013,vegetal,NaN,0.0,76500.0,1.16,...,25.028144,0.000000e+00,0.000000e+00,NaN,NaN,4.364354e+08,1.914653e+04,False,NaN,left_only
299,8,Antigua-et-Barbuda,2560,Coco (Incl Coprah),2013,vegetal,NaN,0.0,77400.0,0.40,...,1.462802,0.000000e+00,0.000000e+00,NaN,NaN,1.093534e+08,1.132209e+03,False,NaN,left_only
300,8,Antigua-et-Barbuda,2561,Sésame,2013,vegetal,NaN,NaN,900.0,NaN,...,18.031160,0.000000e+00,0.000000e+00,NaN,NaN,5.527832e+06,1.622804e+02,False,NaN,left_only
301,8,Antigua-et-Barbuda,2563,Olives,2013,vegetal,NaN,0.0,30600.0,0.09,...,1.172193,0.000000e+00,0.000000e+00,NaN,NaN,3.746862e+07,3.586911e+02,False,NaN,left_only
302,8,Antigua-et-Barbuda,2571,Huile de Soja,2013,vegetal,NaN,0.0,357300.0,10.87,...,0.322562,0.000000e+00,0.000000e+00,NaN,NaN,3.087109e+09,1.152515e+03,False,NaN,left_only
303,8,Antigua-et-Barbuda,2573,Huile de Tournesol,2013,vegetal,NaN,NaN,1800.0,0.06,...,0.284051,0.000000e+00,0.000000e+00,NaN,NaN,1.586583e+07,5.112912e+00,False,NaN,left_only
304,8,Antigua-et-Barbuda,2578,Huile de Coco,2013,vegetal,NaN,NaN,3600.0,0.12,...,0.736426,0.000000e+00,0.000000e+00,NaN,NaN,2.999587e+07,2.651134e+01,False,NaN,left_only
305,8,Antigua-et-Barbuda,2582,Huile de Germe de Maïs,2013,vegetal,NaN,NaN,16200.0,0.49,...,0.763171,0.000000e+00,0.000000e+00,NaN,NaN,1.435222e+08,1.236337e+02,False,NaN,left_only
306,8,Antigua-et-Barbuda,2586,Huil Plantes Oleif Autr,2013,vegetal,NaN,0.0,332100.0,9.83,...,1.071149,0.000000e+00,0.000000e+00,NaN,NaN,2.941849e+09,3.557286e+03,False,NaN,left_only
307,8,Antigua-et-Barbuda,2601,Tomates,2013,vegetal,NaN,NaN,1080000.0,0.09,...,0.941744,2.020948e+08,9.417445e+03,NaN,NaN,2.182624e+08,1.017084e+04,False,NaN,left_only
308,8,Antigua-et-Barbuda,2602,Oignons,2013,vegetal,NaN,0.0,534600.0,0.03,...,1.233296,3.711964e+08,1.233296e+04,NaN,NaN,1.984416e+08,6.593202e+03,False,NaN,left_only
309,8,Antigua-et-Barbuda,2605,"Légumes, Autres",2013,vegetal,NaN,1000000.0,5074200.0,0.27,...,1.296178,1.612048e+09,7.777068e+04,NaN,NaN,1.363309e+09,6.577066e+04,False,NaN,left_only
310,8,Antigua-et-Barbuda,2611,"Oranges, Mandarines",2013,vegetal,NaN,4000000.0,1576800.0,0.00,...,0.443328,1.302155e+09,2.216638e+04,NaN,NaN,4.106478e+08,6.990389e+03,False,NaN,left_only
311,8,Antigua-et-Barbuda,2612,Citrons & Limes,2013,vegetal,NaN,0.0,407700.0,0.03,...,0.435589,0.000000e+00,0.000000e+00,NaN,NaN,8.025109e+07,1.775896e+03,False,NaN,left_only
312,8,Antigua-et-Barbuda,2613,Pamplemousse,2013,vegetal,NaN,0.0,251100.0,NaN,...,0.330219,0.000000e+00,0.000000e+00,NaN,NaN,6.303373e+07,8.291801e+02,False,NaN,left_only
313,8,Antigua-et-Barbuda,2614,"Agrumes, Autres",2013,vegetal,NaN,0.0,117900.0,NaN,...,0.401551,0.000000e+00,0.000000e+00,NaN,NaN,3.064247e+07,4.734291e+02,False,NaN,left_only
314,8,Antigua-et-Barbuda,2615,Bananes,2013,vegetal,NaN,NaN,1027800.0,0.09,...,0.814986,6.156835e+08,8.149862e+03,NaN,NaN,6.327995e+08,8.376428e+03,False,NaN,left_only
315,8,Antigua-et-Barbuda,2616,Bananes plantains,2013,vegetal,NaN,NaN,223200.0,NaN,...,0.770888,0.000000e+00,0.000000e+00,NaN,NaN,1.791496e+08,1.720622e+03,False,NaN,left_only
316,8,Antigua-et-Barbuda,2617,Pommes,2013,vegetal,NaN,1000000.0,186300.0,NaN,...,0.194228,4.049747e+08,1.942278e+03,NaN,NaN,7.544678e+07,3.618464e+02,False,NaN,left_only
317,8,Antigua-et-Barbuda,2618,Ananas,2013,vegetal,NaN,0.0,701100.0,NaN,...,0.305845,4.138921e+08,3.058450e+03,NaN,NaN,2.901797e+08,2.144280e+03,False,NaN,left_only
318,8,Antigua-et-Barbuda,2619,Dattes,2013,vegetal,NaN,0.0,8100.0,NaN,...,1.887146,0.000000e+00,0.000000e+00,NaN,NaN,1.698054e+07,1.528588e+02,False,NaN,left_only
319,8,Antigua-et-Barbuda,2620,Raisin,2013,vegetal,NaN,0.0,379800.0,NaN,...,0.611854,6.239159e+08,6.118539e+03,NaN,NaN,2.369633e+08,2.323821e+03,False,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11193,273,Monténégro,2657,Boissons Fermentés,2013,vegetal,NaN,NaN,770040.0,NaN,...,0.421242,4.510057e+08,4.212424e+03,NaN,NaN,3.472925e+08,3.243735e+03,False,NaN,left_only
11194,273,Monténégro,2658,Boissons Alcooliques,2013,vegetal,NaN,NaN,2036880.0,NaN,...,0.489311,4.469495e+09,9.786210e+03,NaN,NaN,4.551912e+09,9.966668e+03,False,NaN,left_only
11195,273,Monténégro,2680,Aliments pour enfants,2013,vegetal,NaN,NaN,254610.0,0.03,...,15.331439,0.000000e+00,0.000000e+00,NaN,NaN,9.741994e+08,3.903538e+04,False,NaN,left_only
11196,273,Monténégro,2731,Viande de Bovins,2013,animal,NaN,NaN,7818390.0,5.78,...,14.456889,1.356131e+10,1.156551e+06,NaN,NaN,1.325345e+10,1.130296e+06,False,NaN,left_only
11197,273,Monténégro,2732,Viande d'Ovins/Caprins,2013,animal,NaN,NaN,1825740.0,1.84,...,13.861137,4.072026e+09,2.772227e+05,NaN,NaN,3.717230e+09,2.530683e+05,False,NaN,left_only
11198,273,Monténégro,2733,Viande de Suides,2013,animal,NaN,NaN,32937840.0,29.77,...,10.235863,8.333655e+10,3.377835e+06,NaN,NaN,8.317958e+10,3.371472e+06,False,NaN,left_only
11199,273,Monténégro,2734,Viande de Volailles,2013,animal,NaN,NaN,9886320.0,3.26,...,12.623639,1.299476e+10,1.262364e+06,NaN,NaN,1.284703e+10,1.248013e+06,False,NaN,left_only
11200,273,Monténégro,2736,Abats Comestible,2013,animal,NaN,NaN,1446930.0,0.16,...,17.616939,1.133033e+09,1.761694e+05,NaN,NaN,1.639419e+09,2.549048e+05,False,NaN,left_only
11201,273,Monténégro,2737,Graisses Animales Crue,2013,animal,NaN,0.0,428490.0,1.61,...,1.598319,0.000000e+00,0.000000e+00,NaN,NaN,3.243538e+09,6.848639e+03,False,NaN,left_only
11202,273,Monténégro,2740,"Beurre, Ghee",2013,animal,NaN,NaN,1366200.0,4.95,...,0.919332,7.282545e+09,9.193318e+03,NaN,NaN,9.949413e+09,1.255991e+04,False,NaN,left_only
11203,273,Monténégro,2744,Oeufs,2013,animal,NaN,NaN,7203600.0,3.11,...,10.690927,9.547040e+09,7.483649e+05,NaN,NaN,9.824722e+09,7.701316e+05,False,NaN,left_only
11204,273,Monténégro,2745,Miel,2013,vegetal,NaN,NaN,683100.0,NaN,...,0.496510,3.013625e+09,4.965097e+03,NaN,NaN,2.058607e+09,3.391658e+03,False,NaN,left_only
11205,273,Monténégro,2761,Poissons Eau Douce,2013,animal,NaN,0.0,1900260.0,0.20,...,10.519646,1.381348e+09,2.103929e+05,NaN,NaN,1.312460e+09,1.999006e+05,False,NaN,left_only
11206,273,Monténégro,2762,Perciform,2013,animal,NaN,0.0,1595970.0,0.04,...,9.264233,1.261116e+09,1.852847e+05,NaN,NaN,1.006352e+09,1.478544e+05,False,NaN,left_only
11207,273,Monténégro,2763,Poissons Pelagiques,2013,animal,0.0,0.0,1999620.0,0.42,...,12.323581,1.948184e+09,2.464716e+05,NaN,NaN,1.947814e+09,2.464248e+05,False,NaN,left_only
11208,273,Monténégro,2764,"Poissons Marins, Autres",2013,animal,NaN,0.0,583740.0,0.09,...,11.444467,7.902804e+08,1.144447e+05,NaN,NaN,4.613183e+08,6.680593e+04,False,NaN,left_only
11209,273,Monténégro,2765,Crustacés,2013,animal,NaN,0.0,322920.0,0.01,...,9.687512,0.000000e+00,0.000000e+00,NaN,NaN,1.726674e+08,3.128291e+04,False,NaN,left_only
11210,273,Monténégro,2805,Riz (Eq Blanchi),2013,vegetal,NaN,0.0,1391040.0,0.04,...,7.010530,3.640837e+09,7.010530e+04,NaN,NaN,5.064549e+09,9.751927e+04,True,NaN,left_only
11211,273,Monténégro,2848,Lait - Excl Beurre,2013,animal,43000000.0,NaN,216859410.0,31.29,...,3.352396,1.552228e+11,8.883849e+06,1.545547e+11,8.845612e+06,1.270246e+11,7.269986e+06,False,NaN,left_only
11212,273,Monténégro,2513,Orge,2013,vegetal,0.0,4000000.0,18630.0,NaN,...,6.966765,1.778284e+10,4.876736e+05,4.732775e+07,1.297908e+03,4.732775e+07,1.297908e+03,True,NaN,left_only
11213,273,Monténégro,2517,Millet,2013,vegetal,NaN,NaN,12420.0,NaN,...,7.711257,0.000000e+00,0.000000e+00,NaN,NaN,3.842090e+07,9.577382e+02,True,NaN,left_only
11214,273,Monténégro,2549,Légumineuses Autres,2013,vegetal,NaN,NaN,18630.0,NaN,...,22.149204,0.000000e+00,0.000000e+00,NaN,NaN,6.486192e+07,4.126397e+03,False,NaN,left_only
11215,273,Monténégro,2735,"Viande, Autre",2013,animal,NaN,NaN,6210.0,0.00,...,17.525760,0.000000e+00,0.000000e+00,NaN,NaN,8.528509e+06,1.088350e+03,False,NaN,left_only
11216,273,Monténégro,2533,Patates douces,2013,vegetal,NaN,NaN,18630.0,NaN,...,1.086865,0.000000e+00,0.000000e+00,NaN,NaN,1.766304e+07,2.024830e+02,False,NaN,left_only
11217,273,Monténégro,2546,Haricots,2013,vegetal,NaN,NaN,2850390.0,0.21,...,21.855126,1.028622e+10,6.556538e+05,NaN,NaN,9.773246e+09,6.229563e+05,False,NaN,left_only
11218,273,Monténégro,2766,Cephalopodes,2013,animal,NaN,0.0,552690.0,0.02,...,14.405657,9.105962e+08,1.440566e+05,NaN,NaN,5.032774e+08,7.961863e+04,False,NaN,left_only
11219,273,Monténégro,2767,"Mollusques, Autres",2013,animal,NaN,0.0,633420.0,0.01,...,3.038745,2.408515e+08,3.038745e+04,NaN,NaN,1.525602e+08,1.924802e+04,False,NaN,left_only
11220,273,Monténégro,2547,Pois,2013,vegetal,NaN,NaN,1403460.0,0.11,...,22.297166,3.526472e+09,2.229717e+05,NaN,NaN,4.949262e+09,3.129318e+05,False,NaN,left_only
11221,273,Monténégro,2557,Graines de tournesol,2013,vegetal,NaN,NaN,18630.0,0.03,...,11.605517,0.000000e+00,0.000000e+00,NaN,NaN,6.348105e+07,2.162108e+03,False,NaN,left_only
11222,273,Monténégro,2769,Animaux Aquatiques Autre,2013,animal,NaN,0.0,37260.0,0.00,...,4.145809,0.000000e+00,0.000000e+00,NaN,NaN,2.025733e+07,1.544728e+03,False,NaN,left_only

In [100]:
df_disponibilite_al.loc[df_disponibilite_al['_merge'] == 'right_only']

Empty DataFrame
Columns: [code_pays, pays, code_produit, produit, annee, origine, alim_animaux_kg, autres_utilisations_kg, disponibilite_alimentaire_kg_pays_an, disponibilite_de_matiere_grasse_en_quantite_g_personne_jour_, disponibilite_interieure_kg, exportations_quantite_kg, importations_quantite_kg, nourriture_kg, pertes_kg, production_kg, semences_kg, traitement_kg, variation_de_stock_kg, population, disponibilite_alimentaire_kcal_pays_an, disponibilite_proteine_quantite_kg_pays_an, ratio_energie_poids_moyen, pourcentage_proteine_poids_moyen, dispo_inter_kcal, dispo_inter_proteine, humains_animaux_pertes_kcal, humains_animaux_pertes_proteine, dispo_alim_kcal_mondiale_annuelle, dispo_alim_proteine_mondiale_annuelle, is_cereal, pop_sous_al, _merge]
Index: []

[0 rows x 33 columns]

La liste des pays ayant des personnes qui souffrent de malnutrition est proche de la liste de l'ensemble des pays étudiés jusqu'ici, aussi, pour dégager des tendances plus pertinentes, nous considérerons que les pays souffrants de mal nuttrition sont uniquement ceux dont le pourcentage de la population mal nourri est supérieur au pourcentage mondial.

In [101]:
df_disponibilite_al['pourcentage_pop_sous_al'] = 100 * df_disponibilite_al['pop_sous_al'] / df_disponibilite_al['population']

In [102]:
df_disponibilite_al[['pays','pourcentage_pop_sous_al']].loc[df_disponibilite_al['pourcentage_pop_sous_al'] > 100 * df_sous_alimentee['pop_sous_al'].sum() / population_mondiale].drop_duplicates().head(20)

                                 pays  pourcentage_pop_sous_al
60                        Afghanistan                26.512176
231                            Angola                37.257824
729                        Bangladesh                16.858776
852   Bolivie (État plurinational de)                20.616624
918                          Botswana                24.740228
1328                          Myanmar                12.204510
1600        République centrafricaine                45.493934
1649                        Sri Lanka                11.281907
1719                            Tchad                38.206628
1901                            Congo                40.467626
2431           République dominicaine                12.495194
2702                      El Salvador                11.041009
3121                         Djibouti                22.909507
3245                            Gabon                11.961722
3313                           Gambie                10.816658
3769                        Guatemala                16.808896
3837                           Guinée                16.177097
3960                            Haïti                50.402249
4023                         Honduras                16.057312
4295                             Inde                17.018864

Nous trouvons désormais les 15 produit les plus exportés par ces pays :

In [103]:
df_expor_top15 = df_disponibilite_al.loc[df_disponibilite_al['pourcentage_pop_sous_al'] > 100 * df_sous_alimentee['pop_sous_al'].sum() / population_mondiale].groupby(df_disponibilite_al['produit']).sum()
df_expor_top15 = df_expor_top15.reset_index()
df_expor_top15 = df_expor_top15.sort_values(by = 'exportations_quantite_kg', ascending=False).head(15).reset_index(drop=True)
df_expor_top15[['produit','exportations_quantite_kg']]

               produit  exportations_quantite_kg
0     Riz (Eq Blanchi)              2.372700e+10
1                  Blé              1.008600e+10
2               Manioc              9.507000e+09
3                 Maïs              9.256000e+09
4              Bananes              6.784000e+09
5   Lait - Excl Beurre              3.460000e+09
6      Légumes, Autres              3.368000e+09
7       Fruits, Autres              2.783000e+09
8                 Café              2.701000e+09
9                 Noix              2.691000e+09
10    Viande de Bovins              2.075000e+09
11              Ananas              1.894000e+09
12             Oignons              1.893000e+09
13            Haricots              1.762000e+09
14      Huile de Palme              1.435000e+09

Si nous nous contentons d'étudier les 200 plus grandes importations des 15 produits les plus exportés par les pays souffrants de malnutrition, nous nous retrouvons avec 14 produits représentés dans les 200 plus grandes importations. En effet, nous retrouvons plusieurs fois les mêmes 14 produit et l'ananas n'apparait pas. Nous cherchons donc les 220 plus grandes importations de ces 15 produits :

In [104]:
df_disponibilite_al['is_expor_top15'] = df_disponibilite_al.produit.isin(df_expor_top15.produit)

In [105]:
df_impor_top220 = df_disponibilite_al.loc[(df_disponibilite_al['is_expor_top15'] == True) & (df_disponibilite_al['pourcentage_pop_sous_al'] > 100 * df_sous_alimentee['pop_sous_al'].sum() / population_mondiale)].sort_values(by = 'importations_quantite_kg', ascending=False).head(220).reset_index(drop = True)
df_impor_top220[['pays', 'produit', 'importations_quantite_kg']].head()

          pays         produit  importations_quantite_kg
0         Inde  Huile de Palme              8.568000e+09
1         Iraq             Blé              3.607000e+09
2        Yémen             Blé              3.186000e+09
3   Bangladesh             Blé              2.882000e+09
4  Philippines             Blé              2.803000e+09

In [106]:
df_impor_top15 = df_impor_top220.groupby('produit').sum().head(15)
df_impor_top15['ratio_autre_utilisation_dispo_inter_kg_pays'] = df_impor_top15['autres_utilisations_kg'] / df_impor_top15['disponibilite_interieure_kg']
df_impor_top15['ratio_autre_utilisation_dispo_inter_pourcentage_kg_pays'] = 100 * df_impor_top15['autres_utilisations_kg'] / df_impor_top15['disponibilite_interieure_kg']
df_impor_top15['ratio_alim_animaux_humain_kg_pays'] = df_impor_top15['alim_animaux_kg'] / (df_impor_top15['alim_animaux_kg'] + df_impor_top15['disponibilite_alimentaire_kg_pays_an'])
df_impor_top15['ratio_alim_animaux_humain_pourcentage_kg_pays'] = 100 * df_impor_top15['alim_animaux_kg'] / (df_impor_top15['alim_animaux_kg'] + df_impor_top15['disponibilite_alimentaire_kg_pays_an'])
df_impor_top15[['autres_utilisations_kg', 'disponibilite_interieure_kg', 'alim_animaux_kg', 'disponibilite_alimentaire_kg_pays_an', 'ratio_autre_utilisation_dispo_inter_kg_pays','ratio_autre_utilisation_dispo_inter_pourcentage_kg_pays','ratio_alim_animaux_humain_kg_pays','ratio_alim_animaux_humain_pourcentage_kg_pays']]

,autres_utilisations_kg,disponibilite_interieure_kg,alim_animaux_kg,disponibilite_alimentaire_kg_pays_an,ratio_autre_utilisation_dispo_inter_kg_pays,ratio_autre_utilisation_dispo_inter_pourcentage_kg_pays,ratio_alim_animaux_humain_kg_pays,ratio_alim_animaux_humain_pourcentage_kg_pays
produit,,,,,,,,
Bananes,0.000000e+00,4.720000e+08,3.300000e+07,3.930789e+08,0.000000,0.000000,0.077450,7.745045
Blé,3.797000e+09,6.868400e+10,3.754000e+09,5.569777e+10,0.055282,5.528216,0.063144,6.314362
Café,0.000000e+00,3.470000e+08,0.000000e+00,3.414270e+08,0.000000,0.000000,0.000000,0.000000
"Fruits, Autres",0.000000e+00,5.416500e+10,3.400000e+07,4.851447e+10,0.000000,0.000000,0.000700,0.070033
Haricots,0.000000e+00,5.624000e+09,2.260000e+08,4.735033e+09,0.000000,0.000000,0.045555,4.555503
Huile de Palme,1.001500e+10,1.523000e+10,0.000000e+00,5.210191e+09,0.657584,65.758372,0.000000,0.000000
Lait - Excl Beurre,1.830000e+08,7.208600e+10,3.097000e+09,6.385728e+10,0.002539,0.253863,0.046255,4.625544
"Légumes, Autres",0.000000e+00,2.915800e+10,0.000000e+00,2.678546e+10,0.000000,0.000000,0.000000,0.000000
Manioc,3.250000e+08,1.129200e+10,1.420000e+08,1.037915e+10,0.028781,2.878144,0.013497,1.349662
Maïs,1.304000e+09,4.451600e+10,1.763700e+10,2.051588e+10,0.029293,2.929284,0.462272,46.227173
Noix,0.000000e+00,2.224000e+09,0.000000e+00,2.199818e+09,0.000000,0.000000,0.000000,0.000000
Oignons,0.000000e+00,4.577000e+09,0.000000e+00,4.309245e+09,0.000000,0.000000,0.000000,0.000000
Riz (Eq Blanchi),3.370000e+09,7.244400e+10,2.150000e+09,6.009080e+10,0.046519,4.651869,0.034543,3.454326
Viande de Bovins,0.000000e+00,1.404000e+09,0.000000e+00,1.403125e+09,0.000000,0.000000,0.000000,0.000000

Nous cherchons désormais les 3 produits qui ont la plus grande valeur pour chacun des ratios :

In [107]:
df_impor_top15['ratio_autre_utilisation_dispo_inter_pourcentage_kg_pays'].sort_values(ascending = False).head(3)

produit
Huile de Palme      65.758372
Blé                  5.528216
Riz (Eq Blanchi)     4.651869
Name: ratio_autre_utilisation_dispo_inter_pourcentage_kg_pays, dtype: float64

In [108]:
df_impor_top15['ratio_alim_animaux_humain_pourcentage_kg_pays'].sort_values(ascending = False).head(3)

produit
Maïs       46.227173
Bananes     7.745045
Blé         6.314362
Name: ratio_alim_animaux_humain_pourcentage_kg_pays, dtype: float64

### Question 13

Nous chercherons à déterminer le nombre de tonnes de céréales consacrées à l'alimentation des animaux par les USA dans un premier temps. Nous chercherons ensuite à calcluer 10% de ce total et nous les convertirons en tonnes.

In [109]:
(df_disponibilite_al['alim_animaux_kg'].loc[(df_disponibilite_al['is_cereal'] == True) & (df_disponibilite_al['pays'] == 'États-Unis d\'Amérique')].sum() / 1000) * 10 / 100

13970200.0

Nombre de personnes satisfaites en kcal et en proteine :

In [110]:
((df_disponibilite_al['alim_animaux_kg'].loc[(df_disponibilite_al['is_cereal'] == True) & (df_disponibilite_al['pays'] == 'États-Unis d\'Amérique')] * df_disponibilite_al['ratio_energie_poids_moyen']).sum()) / besoin_kcal_personne_annuel

565751536.6212169

In [111]:
((100*(df_disponibilite_al['alim_animaux_kg'].loc[(df_disponibilite_al['is_cereal'] == True) & (df_disponibilite_al['pays'] == 'États-Unis d\'Amérique')] * df_disponibilite_al['ratio_energie_poids_moyen']).sum()) / besoin_kcal_personne_annuel) / (df_population['population'].loc[(df_population['pays'] == 'États-Unis d\'Amérique')])

53    176.769183
Name: population, dtype: float64

In [112]:
df_population['population'].loc[(df_population['pays'] == 'États-Unis d\'Amérique')]

53    320051000
Name: population, dtype: int64

In [113]:
100 * df_population['population'].loc[(df_population['pays'] == 'États-Unis d\'Amérique')] / (df_population['population'].loc[(df_population['pays'] == 'États-Unis d\'Amérique')])

53    100.0
Name: population, dtype: float64

In [114]:
((df_disponibilite_al['alim_animaux_kg'].loc[(df_disponibilite_al['is_cereal'] == True) & (df_disponibilite_al['pays'] == 'États-Unis d\'Amérique')] * df_disponibilite_al['pourcentage_proteine_poids_moyen']).sum() / 100) / besoin_proteine_personne_annuel

498881271.525162

###  Question 14

Nous calculons la proportion de manioc qui est exportée en Thaïland par rapport à la production nationale :

In [115]:
100 * df_disponibilite_al['exportations_quantite_kg'].loc[(df_disponibilite_al['produit'] == 'Manioc') & (df_disponibilite_al['pays'] == 'Thaïlande')] / df_disponibilite_al['production_kg'].loc[(df_disponibilite_al['produit'] == 'Manioc') & (df_disponibilite_al['pays'] == 'Thaïlande')]

9671    83.41273
dtype: float64

In [116]:
df_disponibilite_al['exportations_quantite_kg'].loc[(df_disponibilite_al['produit'] == 'Manioc') & (df_disponibilite_al['pays'] == 'Thaïlande')]

9671    2.521400e+10
Name: exportations_quantite_kg, dtype: float64

Nous observons désormais la proportion de personnes en sous-nutrition :

In [117]:
df_disponibilite_al[['pays','produit','pourcentage_pop_sous_al']].loc[ (df_disponibilite_al['pays'] == 'Thaïlande') & (df_disponibilite_al['produit'] == 'Manioc')].head()

           pays produit  pourcentage_pop_sous_al
9671  Thaïlande  Manioc                 9.102983

## III. Préparation des données questions 15 à 18

In [118]:
# importation des tables 

population = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Questions 15 et suivantes/population.csv')

animaux = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Questions 15 et suivantes/animaux.csv')

vegetaux = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Questions 15 et suivantes/vegetaux.csv')

equilibre_prod = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Questions 15 et suivantes/equilibre_prod.csv')

sous_nutrition = pd.read_csv('/Users/octav/Google Drive/OC_Data Analyst_GORAM Octave/Projets/Projet 3/DF_FAO/Questions 15 et suivantes/sous_nutrition.csv')

In [119]:
# formatage table population

population = population[['Pays','Code Pays','Année','Valeur']]

population.columns = ["pays", "code_pays", "annee", "population"]

population['population'] = population['population'] * 1000

In [120]:
# formatage table dispo_alim

animaux['origine'] = 'animale'

vegetaux['origine'] = 'vegetale'

dispo_alim = animaux.append(vegetaux)

dispo_alim.columns = ['Code Domaine', 'Domaine', 'code_pays', 'pays', 'Code Élément',
       'elément', 'code_produit', 'produit', 'Code Année', 'annee', 'Unité',
       'valeur', 'Symbole', 'Description du Symbole', 'origine']

dispo_alim = dispo_alim.pivot_table(
index=["pays", "code_pays", "annee", "produit", "code_produit", "origine"],
    columns = ["elément"], values=["valeur"], aggfunc=sum)

dispo_alim.columns = ['dispo_alim_kcal_p_j', 'dispo_alim_tonnes', 'dispo_mat_gr', 'dispo_prot']

dispo_alim = dispo_alim.reset_index()

dispo_alim['dispo_alim_tonnes'] = dispo_alim['dispo_alim_tonnes'] / 1000

del animaux, vegetaux

In [121]:
# formatage table equilibre_prod

equilibre_prod.columns = ['Code Domaine', 'Domaine', 'code_pays', 'pays', 'Code Élément',
       'elément', 'code_produit', 'produit', 'Code Année', 'annee', 'Unité',
       'valeur', 'Symbole', 'Description du Symbole']

equilibre_prod = equilibre_prod.pivot_table(
index=["pays", "code_pays", "annee", "produit", "code_produit"],
    columns = ["elément"], values=["valeur"], aggfunc=sum)

equilibre_prod.columns = ['alim_ani','autres_utilisations', 'dispo_int', 'nourriture', 'pertes', 'semences',  'transfo' ]


equilibre_prod = equilibre_prod.reset_index()

In [122]:
# formatage table sous_nutrition

sous_nutrition = sous_nutrition[['Zone','Code zone','Année','Valeur']]

sous_nutrition.columns = ["pays", "code_pays", "annee", "nb_personnes"]

sous_nutrition = sous_nutrition.loc[sous_nutrition.nb_personnes.str.contains("<") == False]

sous_nutrition[['nb_personnes']] = sous_nutrition[['nb_personnes']].astype(float)

sous_nutrition[['nb_personnes']] = sous_nutrition[['nb_personnes']] * 1000000

In [123]:
# supression des pays doublons
population = population.drop(population[population.pays.isin(["Chine - RAS de Hong-Kong", "Chine - RAS de Macao","Chine, continentale","Chine, Taiwan Province de"])].index)

dispo_alim = dispo_alim.drop(dispo_alim[dispo_alim.pays.isin(["Chine - RAS de Hong-Kong", "Chine - RAS de Macao","Chine, continentale","Chine, Taiwan Province de"])].index)

equilibre_prod = equilibre_prod.drop(equilibre_prod[equilibre_prod.pays.isin(["Chine - RAS de Hong-Kong", "Chine - RAS de Macao","Chine, continentale","Chine, Taiwan Province de"])].index)

sous_nutrition = sous_nutrition.drop(sous_nutrition[sous_nutrition.pays.isin(["Chine - RAS de Hong-Kong", "Chine - RAS de Macao","Chine, continentale","Chine, Taiwan Province de"])].index)

In [124]:
# reset index
dispo_alim = dispo_alim.reset_index()

equilibre_prod = equilibre_prod.reset_index()

population = population.reset_index()

sous_nutrition = sous_nutrition.reset_index()

## IV. Questions 15 à 18

###  Question 15

In [125]:
primary_key(population, ['pays','annee'])

This is a Primary key

###  Question 16

In [126]:
primary_key(dispo_alim, ['pays','produit','annee'])

This is a Primary key

###  Question 17

In [127]:
primary_key(equilibre_prod,['pays','produit', 'annee'])

This is a Primary key

###  Question 18

In [128]:
primary_key(df_sous_alimentee,['pays','annee'])

This is a Primary key

## V. Exportation des données

population.to_csv("population.csv", index = False)
dispo_alim.to_csv("dispo_alim.csv", index = False)
equilibre_prod.to_csv("equilibre_prod.csv", index = False)
sous_nutrition.to_csv("sous_nutrition.csv", index = False)